### ISSUE TITLE
Hi can you explain the "16 4" after your script example?

### ISSUE THREAD

**Issue by phd21** [unfa/kdenlive-multirender#14]
Hi unfa,

Thank you for creating this kdenlive multirender script. 

I was wondering if you can explain the "16 4" after your script example? I only have an ancient dual-core computer with 4gb of system memory (ram) and I would like to use both cores / threads, so what would be the numbers after the script command? Whenever I tried this with any numbers after the script command it failed?

Regards,
Phil (phd21)

**Comment by unfa** [comment]
In the example given:
16 - is the number of total chunks that the full project will be split into
4 - is the number of the chunks that;ll be processes in parallel at any given moment.

For a dual-core CPU I guess using 16 2 might be a good start, if you don't saturate your CPU that way - try 16 3 etc. Watch out for your RAM usage - filling that up will deny any speed costs you might have gained as the system will start to swap and that's very slow.

**Comment by phd21** [comment]
Hi unfa,

Thanks for replying so quickly, much appreciated.  Happy Thanksgiving from the USA.

I still cannot get your script to run on my system using any number combinations after the script. So, I thought perhaps if I show you the results that might help. So far, it only works on my system without any numbers after the script. I am using Linux KDE Neon (based on Ubuntu 18.04) and Kdenlive 18.08.3 on a Dell OptiPlex 780 usff with Intel Core2 Duo E8400 with only 2 CPU threads. I use this folder for my Kdenlive projects output and the scripts and I run the scripts from there (/home/user69/Videos/kdenlive/).

Using any number combination after the script does not produce a good video file.... So far...

Thanks for your help. Have a great day and night.

`~/Videos/kdenlive$ bash ./kdenlive-multirender.sh test_11-22-2018_001.sh 4 2 
IN=0 OUT=7671
rm: cannot remove 'kmr-list.txt': No such file or directory
PARTS=4 PART=01 IN= OUT=

PARTS=4 PART=02 IN= OUT=

PARTS=4 PART=03 IN= OUT=

PARTS=4 PART=04 IN= OUT=

Starting thread 01

//STARTING RENDERING:  false , false , "/usr/bin/melt" , "atsc_720p_30" , "avformat" , "-" , "/home/user69/Videos/kdenlive/test_11-22-2018_001.sh.mlt" , "/home/user69/Videos/kdenlive/kmr-untitled-01.webm" , () , ("f=webm", "vcodec=libvpx", "acodec=libvorbis", "crf=15", "vb=0", "quality=good", "aq=7", "max-intra-rate=1000", "cpu-used=4", "progressive=1", "threads=1", "real_time=-1") , 0 , 0
Starting thread 02

//STARTING RENDERING:  false , false , "/usr/bin/melt" , "atsc_720p_30" , "avformat" , "-" , "/home/user69/Videos/kdenlive/test_11-22-2018_001.sh.mlt" , "/home/user69/Videos/kdenlive/kmr-untitled-02.webm" , () , ("f=webm", "vcodec=libvpx", "acodec=libvorbis", "crf=15", "vb=0", "quality=good", "aq=7", "max-intra-rate=1000", "cpu-used=4", "progressive=1", "threads=1", "real_time=-1") , 0 , 0
waiting for a thread to finish...
Starting thread 03

//STARTING RENDERING:  false , false , "/usr/bin/melt" , "atsc_720p_30" , "avformat" , "-" , "/home/user69/Videos/kdenlive/test_11-22-2018_001.sh.mlt" , "/home/user69/Videos/kdenlive/kmr-untitled-03.webm" , () , ("f=webm", "vcodec=libvpx", "acodec=libvorbis", "crf=15", "vb=0", "quality=good", "aq=7", "max-intra-rate=1000", "cpu-used=4", "progressive=1", "threads=1", "real_time=-1") , 0 , 0
Starting thread 04

//STARTING RENDERING:  false , false , "/usr/bin/melt" , "atsc_720p_30" , "avformat" , "-" , "/home/user69/Videos/kdenlive/test_11-22-2018_001.sh.mlt" , "/home/user69/Videos/kdenlive/kmr-untitled-04.webm" , () , ("f=webm", "vcodec=libvpx", "acodec=libvorbis", "crf=15", "vb=0", "quality=good", "aq=7", "max-intra-rate=1000", "cpu-used=4", "progressive=1", "threads=1", "real_time=-1") , 0 , 0
Concatenating files...
ffmpeg version 3.4.4-0ubuntu0.18.04.1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.3.0-16ubuntu3)
  configuration: --prefix=/usr --extra-version=0ubuntu0.18.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  WARNING: library configuration mismatch
  avcodec     configuration: --prefix=/usr --extra-version=0ubuntu0.18.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared --enable-version3 --disable-doc --disable-programs --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libtesseract --enable-libvo_amrwbenc
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
Input #0, concat, from 'kmr-list.txt':
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: vp8, yuv420p(bt709/unknown/bt709, progressive), 1280x720, SAR 1:1 DAR 16:9, 30 fps, 30 tbr, 1k tbn, 1k tbc
    Metadata:
      DURATION        : 00:00:00.033000000
    Stream #0:1: Audio: vorbis, 48000 Hz, stereo, fltp
    Metadata:
      DURATION        : 00:00:00.000000000
Output #0, webm, to '/home/user69/Videos/kdenlive/untitled.webm':
  Metadata:
    encoder         : Lavf57.83.100
    Stream #0:0: Video: vp8, yuv420p(bt709/unknown/bt709, progressive), 1280x720 [SAR 1:1 DAR 16:9], q=2-31, 30 fps, 30 tbr, 1k tbn, 1k tbc
    Metadata:
      DURATION        : 00:00:00.033000000
    Stream #0:1: Audio: vorbis, 48000 Hz, stereo, fltp
    Metadata:
      DURATION        : 00:00:00.000000000
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=    4 fps=0.0 q=-1.0 Lsize=     500kB time=00:00:00.10 bitrate=40934.6kbits/s speed=70.1x    
video:495kB audio:0kB subtitle:0kB other streams:0kB global headers:4kB muxing overhead: 0.923669%
All done!
`

**Comment by unfa** [comment]
Hmm. It looks like it's not calculating the IN/OUT frames for each chunk at all. As you see here, there are no frame numbers provided:
```
PARTS=4 PART=01 IN= OUT=

PARTS=4 PART=02 IN= OUT=

PARTS=4 PART=03 IN= OUT=

PARTS=4 PART=04 IN= OUT=
```
If you have the time to debug it, I'd check why these variables are not being set. Maybe the file format  created by Kdenlive has changed? I have stopped using this script a few months ago, because in the new Kdenlive version the render script  function doens't work, and I prefer to have long rendering times than no auto-save. So I'm not actively working on this script at the moment.
